# docker compose for PostgreSQL
# change the credentials from `.env.example` (remove .example from the filename)
version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports: 
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres-data:
